/* tslint:disable */
/* eslint-disable */
/**
 * PetSitter API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Dog
 */
export interface Dog {
    /**
     * 
     * @type {string}
     * @memberof Dog
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Dog
     */
    age?: number;
    /**
     * 
     * @type {string}
     * @memberof Dog
     */
    breed?: string;
    /**
     * 
     * @type {string}
     * @memberof Dog
     */
    size?: string;
}
