/* tslint:disable */
/* eslint-disable */
/**
 * PetSitter API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface JobApplication
 */
export interface JobApplication {
    /**
     * 
     * @type {string}
     * @memberof JobApplication
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof JobApplication
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof JobApplication
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof JobApplication
     */
    jobId?: string;
}
