/* tslint:disable */
/* eslint-disable */
/**
 * PetSitter API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Dog } from './dog';
/**
 * 
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    creatorUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    endTime?: string;
    /**
     * 
     * @type {string}
     * @memberof Job
     */
    activity?: string;
    /**
     * 
     * @type {Dog}
     * @memberof Job
     */
    dog?: Dog;
}
